# crabgal game configuration
title: "crabgal Demo"
title_background: "bg.webp"

assets:
  bgm:
    v16.wav: "vocal/v16.wav"

fonts:
  speaker_size: 52.0
  dialogue_size: 60.0
  icon_size: 26.0
  label_size: 24.0

styles:
  textbox_alpha: 0.72
  typewriter_speed: 45.0
  auto_delay: 2.0

layout:
  anchor_offset: 40
  sprite_height: 1100
  textbox_left: 7.0
  textbox_dodge_left: 10.0
  textbox_bottom: 1.0
  textbox_height: 22.0
  namebar_bottom: 24.0
